### ISSUE TITLE
START_WITHOUT_PULLUP should not be mentioned for t85_entry_on_power_on_fast_exit_on_no_USB

### ISSUE THREAD

**Issue by Ircama** [ArminJo/micronucleus-firmware#12]
*t85_entry_on_power_on_fast_exit_on_no_USB* does not have *START_WITHOUT_PULLUP*. Assuming that this is correct, its description appears wrong.

**Comment by ArminJo** [comment]
Thank you very much for the issue 🥇 
And sorry for the slow reaction.
