### ISSUE TITLE
Revise utility to write ATtiny85 fuses to 8MHz internal clock

### ISSUE THREAD

**Issue by Ircama** [ArminJo/micronucleus-firmware#15]
I assume you do not have to CKDIV8 [here](https://github.com/ArminJo/micronucleus-firmware/blob/3ef173fda6b782bcf022439d7f8bfc58bdd22e99/utils/Write%2085%20Fuses%20E2%20DF%20FF%20-%20ISP%20Mode%20%3D%208MHz%20without%20BOD%20and%20Pin5.cmd#L17) in order to set the CPU clock to 8 MHz.

`-Ulfuse:w:0x62:m` should be `-Ulfuse:w:0xE2:m`

Is there a reason to also disable SELFPRGEN to speed up restart time from Power Down sleep (or SELFPRGEN is irrelevant for the [purpose of this utility as mentioned here](https://github.com/ArminJo/micronucleus-firmware/blob/3ef173fda6b782bcf022439d7f8bfc58bdd22e99/utils/Write%2085%20Fuses%20E2%20DF%20FF%20-%20ISP%20Mode%20%3D%208MHz%20without%20BOD%20and%20Pin5.cmd#L7))?

**Comment by ArminJo** [comment]
Thanks 👍 
It was a copy paste mistake and disabling SELFPRGEN is only confusing.
