### ISSUE TITLE
Digispark not recognized on Linux machine, but only at boot.

### ISSUE THREAD

**Issue by dentex** [ArminJo/micronucleus-firmware#17]
Hello,
This is not really an issue with your firmware (that I successfully installed on the board), but more a help request :)
In fact I've been having this issue even with the micronucleus version pre-installed (v1.6, IIRC).

Basically, if the board is already connected via USB, early at boot the only message I see with `dmesg` is:
```
[    1.500000] usb 3-2: new low-speed USB device number 3 using xhci_hcd
[    1.600000] usb 3-2: device descriptor read/64, error -71
```
...and nothing works. The device remains unresponsive (and the led is fixed ON).

If the device is plugged **after** the machine booted, all goes well:
```
[   70.858428] usb 3-2: new low-speed USB device number 10 using xhci_hcd
[   71.008647] usb 3-2: New USB device found, idVendor=16d0, idProduct=0753, bcdDevice= 2.05
[   71.008649] usb 3-2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[   76.921597] usb 3-2: USB disconnect, device number 10
```
and then after 6 seconds:
```
[   77.441563] usb 3-2: new low-speed USB device number 11 using xhci_hcd
[   77.901798] usb 3-2: New USB device found, idVendor=16c0, idProduct=27db, bcdDevice= 1.00
[   77.901805] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   77.901808] usb 3-2: Product: DigiKey
[   77.901811] usb 3-2: Manufacturer: digistump.com
[   78.022308] input: digistump.com DigiKey as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/0003:16C0:27DB.0003/input/input28
[   78.082004] hid-generic 0003:16C0:27DB.0003: input,hidraw2: USB HID v1.01 Keyboard [digistump.com DigiKey] on usb-0000:00:14.0-2/input0
```
Do you have any suggestion in regards?
Thanks.

**Comment by ArminJo** [comment]
Sorry, but I have no clue, why the device is stuck when is is connected at boot time. I think, it is more a linux issue than a micronucleus one.
