### ISSUE TITLE
[Question/Feature request] Bootloader clock speed with sub 3.3V supply?

### ISSUE THREAD

**Issue by fijam** [ArminJo/micronucleus-firmware#20]
Hi,

I am concerned about the reliability of the bootloader running at 16.5MHz under less than 3.3V. Would it be possible to have a version running at 12MHz (which is what I think is the minimum for USB operation)?

**Comment by ArminJo** [comment]
This is NOT an issu but a canditate for discussions.
Please try to compile your own bootloader by changing the `F_CPU = 16500000` in Makefile.inc. to  `F_CPU = 12000000` and test it.
I do not own any Hardware to do tests.
