### ISSUE TITLE
Unable to upgrade to new Digistump board version

### ISSUE THREAD

**Issue by Erik84750** [ArminJo/micronucleus-firmware#21]
When replacing the old board preferences descriptor for Digistump with 
https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json
no upgrade in boards manager is possible.
"Java null operation" reported.
Arduino IDE: 1.8.12, W10 64 bit.

**Comment by ArminJo** [comment]
1. You know, that this is not the right repo for this issue?
2. Did you try the latest Arduino 1.8.16 version?
