### ISSUE TITLE
device search times out and platformio

### ISSUE THREAD

**Issue by tcurdt** [ArminJo/micronucleus-firmware#26]
I just tried to flash my digispark usb with platformio.

On the first try it found the usb device and started erasing. Unfortunately that got stuck and I assume the bootloader is gone - and now the device search just times out.

I guess that's related. I assume I will have to use a programmer to bring that back. (Any pointers appreciated!)

And while I am at it - maybe I could go for this firmware instead?
How could one use this firmware with platformio?

https://docs.platformio.org/en/latest/platforms/atmelavr.html#bootloader-programming

**Comment by ArminJo** [comment]
You can burn bootloader just by commandline and avrdude, see https://github.com/ArminJo/micronucleus-firmware/tree/master/utils
