### ISSUE TITLE
programmer type jtagice3_updi not found

### ISSUE THREAD

**Issue by g1ra** [ArminJo/micronucleus-firmware#28]
I have a blue color digispark clone and I'm trying to burn your bootloader , but got an error : 
```
/home/bob/arduino-1.8.5/hardware/tools/avr/bin/avrdude -C/home/bob/.arduino15/packages/digistump/hardware/avr/1.7.5/avrdude.conf -v -pattiny85 -cstk500v1 -P/dev/ttyUSB1 -b19200 -Uflash:w:/home/bob/.arduino15/packages/digistump/hardware/avr/1.7.5/bootloaders/upgrade-t85_entry_on_powerOn_activePullup_fastExit.hex:i 

avrdude: Version 6.3, compiled on Jan 17 2017 at 11:00:16
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/home/bob/.arduino15/packages/digistump/hardware/avr/1.7.5/avrdude.conf"
avrdude: error at /home/bob/.arduino15/packages/digistump/hardware/avr/1.7.5/avrdude.conf:1142: programmer type jtagice3_updi not found
avrdude: error reading system wide configuration file "/home/bob/.arduino15/packages/digistump/hardware/avr/1.7.5/avrdude.conf"
Error while burning bootloader.
```

**Comment by g1ra** [comment]
![bugreport_2022-10-13_08-36-33](https://user-images.githubusercontent.com/1227764/195520379-51ea14ed-76ef-4dcd-9f35-be48ad73ad1e.png)

**Comment by g1ra** [comment]
![bugreport-DSCF9111](https://user-images.githubusercontent.com/1227764/195522702-322e54c0-5afe-48a2-a718-1b540a703ab7.JPG)

**Comment by g1ra** [comment]
led is blinking at plugged in like : 
2blink , long pause (500ms about)
3blink, short pause , 3blink , short pause ..... indefinitely repeats

yesterday flashed a bootloader from your master repo : `
/home/bob/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino18/bin/avrdude -C/home/bob/.arduino15/packages/ATTinyCore/hardware/avr/1.5.2/avrdude.conf -v -pattiny85 -cstk500v1 -P/dev/ttyUSB1 -b19200 -e -U lfuse:w:0xe1:m -U hfuse:w:0xdd:m -U efuse:w:0xfe:m -Uflash:w:t85_entry_on_powerOn_activePullup_fastExit.hex:i `

I did include a 1.5K resistor to P4 (PB4) which is connected by default to USB D- . 
this board have no pullup resistor at P4 by default . 
I did this because : "[ENTRY_D_MINUS_PULLUP_ACTIVATED_AND_ENTRY_POWER_ON](https://github.com/ArminJo/micronucleus-firmware/blob/master/firmware/configuration/t85_entry_on_powerOn_activePullup_fastExit/bootloaderconfig.h#L138) entry condition
Activate the bootloader only if the D- pin is high, i.e. a pull-up resistor is attached and powered and we have an ENTRY_POWER_ON condition (ref. described [above](https://github.com/ArminJo/micronucleus-firmware#entry_power_on-entry-condition))." 

I do **not** understand how can I make ENTRY_POWER_ON condition ..

**Comment by g1ra** [comment]
I'm totally stuck at this point . The MCU does not respond to USB upload .  : 

> attiny85/micronucleus-firmware/firmware/upgrades$ ../../commandline/micronucleus --run /tmp/arduino_build_169828/ATtiny85-note-play.ino.hex
> Please plug in the device ... 
^C

I'm trying plugin , but it  just blinking the led with pattern like described in prev comment (3blink, short pause). 
I think the bootloader expect some boot condition , but Im out of ideas what can I do with it .

I must mention that I did enormous effort to dig into other repos ,trial error , and all stuff , and your repo and README is the best most promising and helpful so far ! 

My attiny85 (MCU) is not bricked . I can make it work with micronucleus-1.11.hex , or with AT85_Bootloader.hex (which I found on a youtube video link to google drive ) . 
I strongly suspect that those bootloaders expect different "conditions" to respond to micronucleus USB upload. ( eg. after > Please plug in the device ..." )

**Comment by g1ra** [comment]
on Windows with Digistump.Drivers the same bootloader works . 
`> Please plug in the device (will time out in 60 seconds) ... 
> Device is found!
connecting: 16% complete
connecting: 22% complete
connecting: 28% complete
connecting: 33% complete
> Device has firmware version 2.6
> Device signature: 0x1e930b 
> Bootloader entry condition: The bootloader is activated if the D- pin is high, i.e. a pullup resistor is attached and powered and a power on condition was detected.
> Bootloader exit condition: The bootloader exits fast (< 1 second) if no USB detected.
> Available space for user applications: 6586 bytes
> Suggested sleep time between sending pages: 7ms
> Whole page count: 103  page size: 64
> Erase function sleep duration: 721ms
parsing: 50% complete
> Erasing the memory ...
erasing: 55% complete
erasing: 60% complete
erasing: 65% complete
> Starting to upload ...
writing: 70% complete
writing: 75% complete
writing: 80% complete
> Starting the user app ...
running: 100% complete
>> Micronucleus done. Thank you!
`

**Comment by ArminJo** [comment]
The **programmer not found** error is not a bug of this repo!
